### PR TITLE
Read secret file before each authentication attempt

### LINKED ISSUE #56: VLC updated but not working
When I update the configmap with the vcl, I get the event log about the template being updated, thought the server is not using the new configuration.

This is the log, at the end there are some error I haven't being able to identify the cause.

```
main.go:31] running kube-httpcache with following options: {Kubernetes:{Config: RetryBackoffString:30s RetryBackoff:30s} Frontend:{Address:0.0.0.0 Port:80 Watch:true Namespace:services Service:kube-httpcache-headless PortName:http} Backend:{Watch:true Namespace:surbtc-staging Service:api Port: PortName:http} Signaller:{Enable:true Address:0.0.0.0 Port:8090 WorkersCount:1 MaxRetries:5 RetryBackoffString:30s RetryBackoff:30s} Admin:{Address:0.0.0.0 Port:6083} Varnish:{SecretFile:/etc/varnish/k8s-secret/secret Storage:malloc,128M AdditionalParameters: VCLTemplate:/etc/varnish/tmpl/default.vcl.tmpl VCLTemplatePoll:false} Readiness:{Enable:true Address:0.0.0.0:9102}}
main.go:38] using in-cluster configuration
run.go:15] waiting for initial configuration before starting Varnish
run.go:35] creating initial VCL config
wait.go:12] probing admin port until it is available
Warnings:
VCL compiled.
Debug: Version: varnish-6.0.7 revision 525d371e3ea0e0c38edd7baf0f80dc226560f26e
Debug: Platform: Linux,4.19.112+,x86_64,-junix,-smalloc,-sdefault,-hcritbit
Debug: Child (29) Started
Info: Child (29) said Child starts
dial.go:41] authentication required. challenge string: "pgsijtgprdlexoqsiivwqwpvwdjxbzdk"
wait.go:23] admin port is available
watch.go:35] received new frontend configuration: &{Endpoints:[{Name:varnish-kube-httpcache-0 Host:10.0.0.180 Port:80 Probe:<nil>} {Name:varnish-kube-httpcache-1 Host:10.0.2.217 Port:80 Probe:<nil>}] Primary:0xc000109580}
dial.go:41] authentication required. challenge string: "ioljpurbdczdxndgmdqybujfqptjbaiy"
endpoints_watch.go:58] endpoints did not change
endpoints_watch.go:58] endpoints did not change
endpoints_watch.go:58] endpoints did not change
endpoints_watch.go:58] endpoints did not change
watch.go:35] received new frontend configuration: &{Endpoints:[{Name:varnish-kube-httpcache-1 Host:10.0.2.217 Port:80 Probe:<nil>}] Primary:0xc000049fc0}
dial.go:41] authentication required. challenge string: "ahxktyozmzdprprgaaaocmmcvzjoztyb"
watch.go:35] received new frontend configuration: &{Endpoints:[{Name:varnish-kube-httpcache-0 Host:10.0.0.93 Port:80 Probe:<nil>} {Name:varnish-kube-httpcache-1 Host:10.0.2.217 Port:80 Probe:<nil>}] Primary:0xc000049fc0}
dial.go:41] authentication required. challenge string: "trcmjlnqogtgtigycxibpatjxerxvcim"
endpoints_watch.go:58] endpoints did not change
watch.go:22] VCL template was updated
dial.go:41] authentication required. challenge string: "cowyknlmtzwpggaevjsxqnlgvnkasxqe"
Security: CLI Authentication failure from telnet 127.0.0.1 37614 127.0.0.1 6083
watch.go:22] VCL template was updated
run.go:53] error while watching for updates: response code was 500, expected 200
dial.go:41] authentication required. challenge string: "jznsdmsaticwukxqqoenhcmhnttwcmca"
Security: CLI Authentication failure from telnet 127.0.0.1 37616 127.0.0.1 6083
run.go:53] error while watching for updates: response code was 500, expected 200
```

**Expected behavior**
I would expect that after the `VCL template was updated` logline the server should respond with the new configuration

**Environment:**
 - Kubernetes version: 1.15
 - kube-httpcache version: latest

### PR DESCRIPTION
**Pull request by bbetter173**
This PR removes the `secret` variable from the controller and instead reads the secret file before each authentication attempt.

Fixes #56 by ensuring that the correct password is used for all reloads.

Relevant varnish docs: https://github.com/varnishcache/varnish-cache/blob/606977bbfb624ead38e9c8648beac0b3906a4294/doc/sphinx/users-guide/run_security.rst#cli-interface-authentication, specifically: 

> You can change the contents of the secret file while varnishd runs, it is read every time a CLI connection is authenticated.

### CODE REVIEW

**Comment by HeWhoWas** [comment]
@martin-helmich - Sorry to ping, but any chance this could be reviewed before it's closed off as stale? Thanks!

**Comment by HeWhoWas** [comment]
Can we please remove the stale tag?

**Comment by martin-helmich** [comment]
Apologies. This should not have gotten stale.

**Review by martin-helmich — APPROVED** [review]
:+1: LGTM -- thanks for your contribution.

**Comment by robmoore** [comment]
I believe we have been seeing this issue in our environment. It doesn't appear that this change made it to 0.7.0. Is it possible it may be included in a release soon?

**Pull request merged**
